'use strict'
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path')
const {deriveParameterViews}=require('./parameterDeclaration'),{resolveEngineProfile}=require('./profile'),{acceptedRequestKeys}=require('./paramTable'),{buildHostProfile}=require('./hostProfile')
const ROOT=path.resolve(__dirname,'..','..'),raw=JSON.parse(fs.readFileSync(path.join(ROOT,'engines','indextts2','manifest.json'),'utf8')),manifest=deriveParameterViews(raw),profile=resolveEngineProfile('indextts2',{})
const LOAD=['use_fp16','use_cuda_kernel','use_deepspeed','use_accel','use_torch_compile'],CALL=['emo_alpha','interval_silence','verbose','max_text_tokens_per_segment','emo_audio_prompt','emo_vector','use_emo_text','emo_text','use_random'],PLATFORM=['format','split','max_chars','concat','silence_ms','media_type','engine_batch','voice_label']
test('004：IndexTTS2 参数只维护在 parameters',()=>{assert.ok(Array.isArray(raw.parameters));for(const k of ['param_keys','payload_keys','params','defaults','defaults_env'])assert.equal(Object.hasOwn(raw,k),false);assert.deepEqual(raw.parameters.map(p=>p.name),[...LOAD,...CALL])})
test('004：派生 call/load 与 Payload 白名单保持既有事实',()=>{assert.deepEqual(manifest.params.load_time,LOAD);assert.deepEqual(manifest.params.call_time,CALL);assert.deepEqual(manifest.payload_keys,CALL);assert.deepEqual(manifest.param_keys,[...LOAD,...CALL])})
test('004：Broker maps 原样保留',()=>assert.deepEqual(profile.maps,{text:'text',reference_audio:'ref_audio_path',seed:'seed',media_type:'media_type'}))
test('004：平台键不混入 param_keys 但仍被接收',()=>{const a=acceptedRequestKeys();for(const k of PLATFORM){assert.equal(profile.param_keys.includes(k),false);assert.equal(a.has(k),true)}})
test('004：call 参数 UI 值与条件保持',()=>{const b=new Map(profile.param_schema.map(p=>[p.name,p]));assert.equal(b.get('emo_alpha').default,1);assert.equal(b.get('interval_silence').default,200);assert.equal(b.get('verbose').default,false);assert.equal(b.get('max_text_tokens_per_segment').default,120);assert.equal(b.get('emo_audio_prompt').default,'');assert.deepEqual(b.get('emo_vector').default,[0,0,0,0,0,0,0,0]);assert.equal(b.get('use_emo_text').default,false);assert.equal(b.get('emo_text').default,'');assert.deepEqual(b.get('emo_text').only_when,{use_emo_text:true});assert.equal(b.get('use_random').default,false)})
test('004：load 参数进入 Advanced/runtime 且无建议值',()=>{const b=new Map(profile.param_schema.map(p=>[p.name,p])),d=new Map(raw.parameters.map(p=>[p.name,p]));for(const[i,k]of LOAD.entries()){const f=b.get(k);assert.equal(d.get(k).phase,'load');assert.equal(f.type,'boolean');assert.equal(f.tier,'advanced');assert.equal(f.group,'runtime');assert.equal(f.order,(i+1)*10);assert.equal(Object.hasOwn(f,'default'),false);assert.ok(f.label.en&&f.label.zh&&f.help.en&&f.help.zh)}})
test('004：静态构造参数保持不变',()=>assert.deepEqual(buildHostProfile('indextts2',{}).call.init_args,{cfg_path:'{checkpoints}/config.yaml',model_dir:'{checkpoints}',use_fp16:true,use_cuda_kernel:false,use_deepspeed:false}))
test('004：GSV 继续走旧声明路径',()=>{const r=JSON.parse(fs.readFileSync(path.join(ROOT,'engines','gpt-sovits','manifest.json'),'utf8'));assert.equal(Object.hasOwn(r,'parameters'),false);const g=resolveEngineProfile('gpt-sovits',{});assert.ok(g.param_keys.length&&g.payload_keys.length)})
